### ISSUE TITLE
encode_example.pyで作成した文字列に誤り

### ISSUE THREAD

**Issue by GynRoyal** [Miyabi-ill/CharmExporterForMHRiseSkillSim#1]
状態：同上

原因の箇所：
①
https://github.com/Miyabi-ill/CharmExporterForMHRiseSkillSim/blob/a008f5b760d065606d2bda420c12f851d08a4a5e/encode_example.py#L22
②
https://github.com/Miyabi-ill/CharmExporterForMHRiseSkillSim/blob/a008f5b760d065606d2bda420c12f851d08a4a5e/encode_example.py#L33-L35

解決例：
①
`skill2_array += encoded_skill2`
②
`header_value = [0x08,0x10,0x18]`
`for i,slot in enumerate(slots):`
`    array += [header_value[i], slot]`

**Comment by Miyabi-ill** [comment]
ありがとうございます。修正しますね。
