### ISSUE TITLE
多数の護石を変換した際のエラー

### ISSUE THREAD

**Issue by nanamaki** [Miyabi-ill/CharmExporterForMHRiseSkillSim#2]
### 環境
* OS: Windows10 `build 19042.964`
* Architecture: x64
* Browser: Google Chrome `90.0.4430.93`

### 問題
護石を多数(手元の環境では870個を超えたあたり)選択して変換した際、base64エンコード後の文字数が50000文字を超えてスプレッドシートの1セル50000文字の制限でエラー表示となりました。

スプレッドシートやGASの使い方に明るくないのですが、1セル文字数制限を回避する方法はあるでしょうか。

**Comment by Miyabi-ill** [comment]
ありがとうございます！調べたところ、50000文字制限を設定などで回避する方法はないようなので、関数の出力を複数セルに分割することで回避するようにします。
